### ISSUE TITLE
Disabling dependency on Ceres does not work completely

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/parPE#145]
When disabling the dependency on Ceres in the cmake options, the build still fails due to implicit dependency on Ceres in
 - unittests, which use Ceres
 - the steadystate example, which uses Ceres
This should be somehow circumvented. PARPE_ENABLE_CERES = off should disable really all Ceres dependencies...

**Comment by dweindl** [comment]
*ping*

**Comment by paulstapor** [comment]
Seems like the problem vanished after my last merge... (?)
Got it running, after disabling Ceres, but having the examples and tests enabled...
