### ISSUE TITLE
Deal with stale branches

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/parPE#200]
> minibatch_more_examples Updated 9 months ago by paulstapor
> improvments_minibatch Updated 5 months ago by paulstapor

@paulstapor : Could you please check the branches above if they contain relevant contributions or if they are to be removed?

**Comment by paulstapor** [comment]
Had a look:
improvements_minibatch should be merged, as there are new algorithms in this one...

**Comment by dweindl** [comment]
One done. Left with `minibatch_more_examples`

**Comment by paulstapor** [comment]
that one, I'm pretty sure you can kill...
