### ISSUE TITLE
Save parameter Ids in simulation results file

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/parPE#230]
At the moment, only parameter values are saved in the simulation h5 file but no parameter Ids.
Also, the parameter length is different from the optimization parameter vector (simulate file has more parameters than optimization results file)

**Comment by LeonardSchmiester** [comment]
Also observable Ids and condition ids would be good, to have all infos in one file

**Comment by dweindl** [comment]
TODO
- [ ] copy relevant input data to simulation file (esp. condition ids) (#120)
- [ ] save problem parameter values
- [ ] save problem parameter ids
- [ ] save mapped parameters per simulation condition?

**Comment by dweindl** [comment]
With #259 these data should be there. Simulation result hdf5 files should now contain `/inputData` (same as optimization results), and along with the other simulation results, there is now also a `parameters` group with simulation parameters for the individual conditions and some additional datasets with IDs.
