### ISSUE TITLE
invalidate/LLH/SLLH should stay part of public API of rdata

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/parPE#279]
Recently, the functions rdata->invalidate(), invalidateLLH(), and invalidateSLLH() have been moved to the protected API of ReturnData:
https://github.com/ICB-DCM/AMICI/blob/6313a226391d7dc114c987a67f3b4697cc5f6ab7/include/amici/rdata.h#L561

However, parPE uses them, if failure of the objective function occurs.
https://github.com/ICB-DCM/parPE/blob/142271cafa394b92accbdd059979b553750a01c0/src/parpeamici/multiConditionProblem.cpp#L442
What speaks against having/keeping those members in the public API? I don't know 100% the purpose of calling those functions in parPE (would have to ask @dweindl ), but I would guess it's there for some good reason.

**Comment by dweindl** [comment]
There have been quite some changes in the C++ code. There may be a number of other and less trivial adaptations required.

**Comment by paulstapor** [comment]
I already stumbled across some of them... working at it...

**Comment by paulstapor** [comment]
If you have some things in mind, happy to get help, but obviously, you don't have to, so don't feel pushed.

**Comment by dweindl** [comment]
@paulstapor Is this still an issue?

**Comment by paulstapor** [comment]
No, solved on develop since quite a while.
